name: Action-1

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [main]

jobs:
  merge-to-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Jira module
        run: pip install jira

      - name: Check Jira ticket status
        env:
          JIRA_API_KEY: ${{ secrets.JIRA_API_KEY }}
        run: |
          pr_title=$(echo "${{ github.event.pull_request.title }}" | grep -oP "(?<=\\[).*?(?=\\])")
          if [[ -z "$pr_title" ]]; then
            echo "PR title doesn't contain a Jira ticket reference. Merge to develop is allowed."
            exit 0
          else
            jira_ticket="$(grep -E '[A-Z|a-z]{1,}\-[0-9]{1,}' <<< "$pr_title")"
            jira_ticket_status="$(curl -u "${{secrets.JIRA_USERNAME}}":"${{secrets.JIRA_API_KEY}}" -X GET -H "Content-Type: application/json" "https://${{secrets.JIRA_HOST}}/rest/api/2/issue/${jira_ticket}?fields=status" | jq '.fields.status.name')"
            if [[ "$jira_ticket_status" == "REVIEW" ]]; then
              echo "Jira ticket $pr_title is marked as Resolved. Merge to develop is allowed."
              exit 0
            else
              echo "Jira ticket $pr_title is not marked as Resolved. Merge to develop is not allowed."
              exit 1
            fi
          fi
